networks:
  shopflow-network:
    external: true
services:
  shopflow-order:
    build:
      context: .
      args:
        SERVICE_NAME: shopflow-order
    container_name: shopflow-order
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=shopflow_kafka:9092
      - SPRING_DATA_REDIS_HOST=shopflow_redis
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://shopflow_zipkin:9411/api/v2/spans
      - JAVA_TOOL_OPTIONS=-Xmx300m -Xms300m
    depends_on:
      - kafka
      - redis
    networks:
      - shopflow-network
  shopflow-identity:
    build:
      context: .
      args:
        SERVICE_NAME: shopflow-identity
    container_name: shopflow-identity
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=shopflow_kafka:9092
      - SPRING_DATA_REDIS_HOST=shopflow_redis
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://shopflow_zipkin:9411/api/v2/spans
      - JAVA_TOOL_OPTIONS=-Xmx300m -Xms300m
    depends_on:
      - kafka
      - redis
    networks:
      - shopflow-network
  shopflow-inventory:
    build:
      context: .
      args:
        SERVICE_NAME: shopflow-inventory
    container_name: shopflow-inventory
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=shopflow_kafka:9092
      - SPRING_DATA_REDIS_HOST=shopflow_redis
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://shopflow_zipkin:9411/api/v2/spans
      - JAVA_TOOL_OPTIONS=-Xmx300m -Xms300m
    depends_on:
      - kafka
      - redis
    networks:
      - shopflow-network
  shopflow-payment:
    build:
      context: .
      args:
        SERVICE_NAME: shopflow-payment
    container_name: shopflow-payment
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=shopflow_kafka:9092
      - SPRING_DATA_REDIS_HOST=shopflow_redis
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://shopflow_zipkin:9411/api/v2/spans
      - JAVA_TOOL_OPTIONS=-Xmx300m -Xms300m
    depends_on:
      - kafka
      - redis
    networks:
      - shopflow-network
  shopflow-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: shopflow-gateway
    container_name: shopflow-gateway
    ports:
      - "8080:8888"
    env_file:
      - .env
    environment:
      - IDENTITY_SERVICE_URL=http://shopflow-identity:8082
      - ORDER_SERVICE_URL=http://shopflow-order:8081
      - INVENTORY_SERVICE_URL=http://shopflow-inventory:8083
      - PAYMENT_SERVICE_URL=http://shopflow-payment:8084
      - SPRING_DATA_REDIS_HOST=shopflow_redis
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://shopflow_zipkin:9411/api/v2/spans
      - JAVA_TOOL_OPTIONS=-Xmx300m -Xms300m
    depends_on:
      - redis
    networks:
      - shopflow-network
  shopflow-notification:
    build:
      context: .
      args:
        SERVICE_NAME: shopflow-notification
    container_name: shopflow-notification
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=shopflow_kafka:9092
      - SPRING_DATA_REDIS_HOST=shopflow_redis
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://shopflow_zipkin:9411/api/v2/spans
      - JAVA_TOOL_OPTIONS=-Xmx200m -Xms200m
    depends_on:
      - kafka
      - redis
    networks:
      - shopflow-network