server:
  port: 8084
spring:
  application:
    name: shopflow-payment
  datasource:
    url: jdbc:postgresql://localhost:5436/${POSTGRES_PAYMENT_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: shopflow-payment-group
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 10
          min-idle: 2

momo:
  payment:
    partner-code: "MOMO..."
    access-key: "..."
    secret-key: "..."
    api-endpoint: "https://test-payment.momo.vn/v2/gateway/api/create"
    return-url: "http://localhost:3000/payment-result"
    ipn-url: "https://abcd.ngrok-free.app/api/v1/payments/momo-ipn"

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
